

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class TextBlock;
                ref class StackPanel;
                ref class TextBox;
            }
        }
    }
}

namespace woblight
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ rectangle_background;
        private: ::Windows::UI::Xaml::Controls::Image^ image_woblightOverlay;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textblock_CustomOverlay;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ stackpanel_MainMenu;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ stackpanel_CustomWobMenu;
        private: ::Windows::UI::Xaml::Controls::TextBox^ customWobInput;
    };
}

